server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MAPS-SERVICE
          uri: lb://MAPS-SERVICE
          predicates:
            - Path=/Map/**
        - id: ATTRACTIONS-SERVICE
          uri: lb://ATTRACTIONS-SERVICE
          predicates:
            - Path=/Attractions/**
        - id: DIANS-APP
          uri: lb://DIANS-APP
          predicates:
            - Path=/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost